name: build with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  check:
    runs-on: ubuntu-22.04
    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Java version
        run: |-
          java -version
          mvn -v

      - name: Maven test
        run: mvn test

      - name: Check build
        run: mvn package

  build:
    needs: check
    runs-on: ubuntu-22.04
    if: github.event_name == 'push'

    steps:
    - name: Setup repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Extract tag
      run: echo "tag=$(git describe --tags --always)" >> $GITHUB_ENV

    - name: Build with Maven
      run: mvn versions:set -DnewVersion=${{ env.tag }} && mvn package
  
    - name: Upload zip to s3 bucket
      run: aws s3 cp target/subtitle-${{ env.tag }}-jar-with-dependencies.jar s3://nomalab-releases
      env:
        AWS_DEFAULT_REGION: "eu-west-1"
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
